sudo: required

language: php

php:
  - 7.4
  - 8.0
  - 8.1

branches:
  only:
  - master

before_script:
  - composer install --no-interaction --no-suggest
  - composer require php-coveralls/php-coveralls

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml tests

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

notifications:
  email:
    recipients:
      - info@miladrahimi.com
    on_success: change
    on_failure: always
